development:
  adapter: sqlite3
  database: sqlprac.db
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sqlapps
  pool: 5
  username: root
  password:
  host: db
  port: 3306