default:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sqlapps
  pool: 5
  username: root
  password: 
  host: db
  port: 3306

development:
  <<:
  database: sqlapps_development

test:
  <<:
  database: sqlapps_development

production:
  <<:
  database: sqlapps_production