development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sqlapp_development
  pool: 5
#  username: <%= ENV["MYSQL_USERNAME"] %>
#  password: <%= ENV["MYSQL_PASSWORD"] %>
  username: sqlapp
  password: sqlappsqlapp
  host: localhost
test:
  <<:
  database: sqlapps_development

production:
  <<:
  database: sqlapps_production