default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  port: 3306

development:
  <<: *default
  host: development-db
  database: sqlapp_development
  
test:
  <<: *default
  host: test-db
  database: sqlapp_test

production:
  <<: *default
  host: production-db
  database: sqlapp_production