development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sqlapp_development
  pool: 5
  username: root
  password:
  host: db
  port: 3306
test:
  <<:
  database: sqlapps_development

production:
  <<:
  database: sqlapps_production