FROM ruby:2.6.0

WORKDIR /app
COPY ./Gemfile Gemfile
COPY ./Gemfile Gemfile.lock

RUN apt-get update && \
    apt-get -y install mysql-client && \
    gem install bundler && \
    gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/' && \
    bundle install

COPY . /app



