version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_Sinatra
    ports:
      - "4567:4567"
    tty: true
    command: >
      bash -c 'sh ./entrypoint.sh development-db &&
      APP_ENV=development bundle exec rake db:migrate &&
      APP_ENV=development bundle exec rake db:seed &&
      APP_ENV=development bundle exec rackup -o 0.0.0.0 -p 4567'
    depends_on:
      - development-db

  development-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "sqlapp_development"
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
