version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    depends_on:
      - db
    command: bundle exec rackup -p 4567

  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "sqlapps"
      MYSQL_USER: "root"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"