version: "3"

services:
  web:
    build: .
    ports:
      - "4567:4567"
    tty: true
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "sqlapps"
      MYSQL_USER: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"