version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_Sinatra
    ports:
      - "4567:4567"
    tty: true
    command: >
      bash -c 'sh ./entrypoint.sh test-db &&
      APP_ENV=test bundle exec rake db:migrate &&
      APP_ENV=test bundle exec rspec ./spec'
    depends_on:
      - test-db

  test-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "sqlapp_test"
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"